baseURL = 'https://blog.dhanuja.com/'
languageCode = 'en-us'
title = 'Dhanuja’s Delta Logs'
theme = "PaperMod"

[params]
  defaultTheme = "light"
  copyright = "© 2025 Dhanuja’s Delta Logs · Created by Dhanuja Ranawake"